name: web3

contracts_folder: contracts

compiler:
  vyper:
    version: 0.4.0
    settings:
      evm_version: "paris"
      optimize: true
      exclude_paths: []
      include_paths: []

ethereum:
  custom:
    host: https://rpc-animechain-39xf6m45e3.t.conduit.xyz
    chain_id: 69000
    default_provider: web3

networks:
  custom:
    - name: custom
      chain_id: 69000
      ecosystem: ethereum
      default_provider: node
    arbitrum-goerli:
      chain_id: 421613
      provider: https://arb-goerli.g.alchemy.com/v2/
    ethereum-sepolia:
      chain_id: 11155111
      provider: https://sepolia.infura.io/v3/G/
node:
  ethereum:
    custom:
      uri: https://rpc-animechain-39xf6m45e3.t.conduit.xyz