name: web3

contracts_folder: contracts

compiler:
  name: vyper
  version: 0.4.0
  settings:
    evm_version: "paris"
    optimize: true
    exclude_paths: []
    include_paths: []

ethereum:
  custom:
    host: https://rpc-animechain-39xf6m45e3.t.conduit.xyz
    chain_id: 69000
