name: web3

contracts_folder: contracts

plugins:
  - name: vyper
  - name: alchemy
  - name: arbitrum

compiler:
  vyper:
    version: 0.4.1
    settings:
      evm_version: "paris"
      optimize: true
      exclude_paths: []
      include_paths: []
    output_formats:
      - abi
      - bytecode
      - source_map
      - source_map_runtime
      - source_map_sources
      - source_map_sources_runtime

ethereum:
  mainnet:
    default_provider: alchemy
  sepolia:
    default_provider: alchemy
  custom:
    host: https://rpc-animechain-39xf6m45e3.t.conduit.xyz
    chain_id: 69000
    default_provider: web3
  
node:
  ethereum:
    custom:
      uri: https://rpc-animechain-39xf6m45e3.t.conduit.xyz
    goerli:
      uri: https://eth-goerli.g.alchemy.com/
    sepolia:
      uri: https://eth-sepolia.g.alchemy.com/
