name: web3

contracts_folder: contracts

plugins:
  - name: vyper
  - name: alchemy

compiler:
  vyper:
    version: 0.4.0
    settings:
      evm_version: "paris"
      optimize: true
      exclude_paths: []
      include_paths: []

ethereum:
  custom:
    host: https://rpc-animechain-39xf6m45e3.t.conduit.xyz
    chain_id: 69000
    default_provider: web3

networks:
  custom:
    - name: custom
      chain_id: 69000
      ecosystem: ethereum
      default_provider: node
  goerli:
    provider: alchemy
  mainnet:
    provider: infura
    
node:
  ethereum:
    custom:
      uri: https://rpc-animechain-39xf6m45e3.t.conduit.xyz